const fs = require('fs');
const path = require('path');
const glob = require('glob');
const rimraf = require('rimraf');
const pascalCase = require('pascal-case');

// dir generated by sketch export
const DIR_SRC = path.join(__dirname, '../../dist/Icon');

// destination to move all icons to
const DIR_DEST = path.join(__dirname, '../../dist/raw/');

if (!fs.existsSync(DIR_DEST)) {
  fs.mkdirSync(DIR_DEST);
}

/**
 * @param {Array} filePaths absolute paths to all svgs exported from sketch
 * @param {String} destination desired destination for cleaned up exports
 * @param {Function} cbFn callback when move is complete
 */
const moveFiles = (filePaths, destination, cbFn) => {
  const fileNames = filePaths.map(
    (filePath) => `${pascalCase(path.basename(filePath, '.svg'))}.svg`
  );

  filePaths.forEach((filePath, i) => {
    fs.renameSync(filePath, `${destination}${fileNames[i]}`);
  });

  if (cbFn) cbFn();
};

module.exports = () => {
  glob(`${DIR_SRC}/**/*.svg`, {}, (error, files) => {
    if (error) throw new Error(`glob error: ${error}`);

    // move all exported icons into a single dir
    // with pascal-cased file names
    moveFiles(files, DIR_DEST, () => {
      // clean up dirs generated by sketch
      rimraf.sync(`${DIR_SRC}`);
    });
  });
};
