exports.svgoOptions = {
  floatPrecision: 3,
  multipass: true,
};

exports.svgoPlugins = [
  { cleanupAttrs: true },
  { removeDoctype: true },
  { removeXMLProcInst: true },
  { removeComments: true },
  { removeMetadata: true },
  { removeTitle: true },
  { removeDesc: true },
  { removeUselessDefs: true },
  { removeEditorsNSData: true },
  { removeEmptyAttrs: true },
  { removeHiddenElems: true },
  { removeEmptyText: true },
  { removeEmptyContainers: true },
  { removeViewBox: false },
  { cleanupEnableBackground: true },
  { convertStyleToAttrs: false },
  { convertColors: true },
  { convertPathData: false },
  { convertTransform: false },
  { removeUnknownsAndDefaults: true },
  { removeNonInheritableGroupAttrs: true },
  { removeUselessStrokeAndFill: true },
  { removeUnusedNS: true },
  { cleanupNumericValues: true },
  { moveElemsAttrsToGroup: false },
  { moveGroupAttrsToElems: false },
  { collapseGroups: false },
  { removeRasterImages: false },
  { mergePaths: false },
  { convertShapeToPath: false },
  { sortAttrs: true },
  { removeDimensions: true },
  { removeAttrs: { attrs: '(stroke|fill)' } },
];
