/**
* DO NOT EDIT
* Generated by fds-dictionary on Thu Nov 11 2021 15:24:47 GMT-0600 (Central Standard Time)
* github.com/cbinsights/form-design-system/
*/


export const colors = [
  {
    "varNames": {
      "css": "var(--color-charcoal)",
      "js": "COLOR_CHARCOAL",
      "human": "charcoal"
    },
    "values": {
      "hex": "404040",
      "calculated": "#404040",
      "rgba": "rgba(64, 64, 64, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-slate)",
      "js": "COLOR_SLATE",
      "human": "slate"
    },
    "values": {
      "hex": "757575",
      "calculated": "#757575",
      "rgba": "rgba(117, 117, 117, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-gray)",
      "js": "COLOR_GRAY",
      "human": "gray"
    },
    "values": {
      "hex": "a2a0a0",
      "calculated": "#a2a0a0",
      "rgba": "rgba(162, 160, 160, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-silver)",
      "js": "COLOR_SILVER",
      "human": "silver"
    },
    "values": {
      "hex": "c2bfbf",
      "calculated": "#c2bfbf",
      "rgba": "rgba(194, 191, 191, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-timberwolf)",
      "js": "COLOR_TIMBERWOLF",
      "human": "timberwolf"
    },
    "values": {
      "hex": "d6d4d4",
      "calculated": "#d6d4d4",
      "rgba": "rgba(214, 212, 212, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-lightGray)",
      "js": "COLOR_LIGHT_GRAY",
      "human": "lightGray"
    },
    "values": {
      "hex": "f2f2f2",
      "calculated": "#f2f2f2",
      "rgba": "rgba(242, 242, 242, 1)",
      "hsla": "hsla(0,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-white)",
      "js": "COLOR_WHITE",
      "human": "white"
    },
    "values": {
      "hex": "ffffff",
      "calculated": "#ffffff",
      "rgba": "rgba(255, 255, 255, 1)",
      "hsla": "hsla(0,0,1,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-navy)",
      "js": "COLOR_NAVY",
      "human": "navy"
    },
    "values": {
      "hex": "003366",
      "calculated": "#003366",
      "rgba": "rgba(0, 51, 102, 1)",
      "hsla": "hsla(210,1,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-blue)",
      "js": "COLOR_BLUE",
      "human": "blue"
    },
    "values": {
      "hex": "006699",
      "calculated": "#006699",
      "rgba": "rgba(0, 102, 153, 1)",
      "hsla": "hsla(199,1,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-aqua)",
      "js": "COLOR_AQUA",
      "human": "aqua"
    },
    "values": {
      "hex": "4cabce",
      "calculated": "#4cabce",
      "rgba": "rgba(76, 171, 206, 1)",
      "hsla": "hsla(196,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-sky)",
      "js": "COLOR_SKY",
      "human": "sky"
    },
    "values": {
      "hex": "bbdbe5",
      "calculated": "#bbdbe5",
      "rgba": "rgba(187, 219, 229, 1)",
      "hsla": "hsla(194,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-haze)",
      "js": "COLOR_HAZE",
      "human": "haze"
    },
    "values": {
      "hex": "f1f5f7",
      "calculated": "#f1f5f7",
      "rgba": "rgba(241, 245, 247, 1)",
      "hsla": "hsla(199,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-red)",
      "js": "COLOR_RED",
      "human": "red"
    },
    "values": {
      "hex": "e5323e",
      "calculated": "#e5323e",
      "rgba": "rgba(229, 50, 62, 1)",
      "hsla": "hsla(355,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-orange)",
      "js": "COLOR_ORANGE",
      "human": "orange"
    },
    "values": {
      "hex": "ff6633",
      "calculated": "#ff6633",
      "rgba": "rgba(255, 102, 51, 1)",
      "hsla": "hsla(15,1,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-sienna)",
      "js": "COLOR_SIENNA",
      "human": "sienna"
    },
    "values": {
      "hex": "f9a862",
      "calculated": "#f9a862",
      "rgba": "rgba(249, 168, 98, 1)",
      "hsla": "hsla(27,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-sand)",
      "js": "COLOR_SAND",
      "human": "sand"
    },
    "values": {
      "hex": "fcc89a",
      "calculated": "#fcc89a",
      "rgba": "rgba(252, 200, 154, 1)",
      "hsla": "hsla(28,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-green)",
      "js": "COLOR_GREEN",
      "human": "green"
    },
    "values": {
      "hex": "00986b",
      "calculated": "#00986b",
      "rgba": "rgba(0, 152, 107, 1)",
      "hsla": "hsla(162,1,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-mint)",
      "js": "COLOR_MINT",
      "human": "mint"
    },
    "values": {
      "hex": "70c390",
      "calculated": "#70c390",
      "rgba": "rgba(112, 195, 144, 1)",
      "hsla": "hsla(143,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-purple)",
      "js": "COLOR_PURPLE",
      "human": "purple"
    },
    "values": {
      "hex": "a02385",
      "calculated": "#a02385",
      "rgba": "rgba(160, 35, 133, 1)",
      "hsla": "hsla(312,0,0,1)"
    }
  },
  {
    "varNames": {
      "css": "var(--color-violet)",
      "js": "COLOR_VIOLET",
      "human": "violet"
    },
    "values": {
      "hex": "d772ad",
      "calculated": "#d772ad",
      "rgba": "rgba(215, 114, 173, 1)",
      "hsla": "hsla(324,0,0,1)"
    }
  }
];
export const mediaQueries = [
  {
    "mqInfo": {
      "size": "xs",
      "usage": "@media (--viewport-xs)",
      "query": "(min-width: 480px)",
      "description": "targets viewports xs and larger"
    },
    "value": "(min-width: 480px)",
    "attributes": {
      "category": "customMedia"
    }
  },
  {
    "mqInfo": {
      "size": "s",
      "usage": "@media (--viewport-s)",
      "query": "(min-width: 640px)",
      "description": "targets viewports s and larger"
    },
    "value": "(min-width: 640px)",
    "attributes": {
      "category": "customMedia"
    }
  },
  {
    "mqInfo": {
      "size": "m",
      "usage": "@media (--viewport-m)",
      "query": "(min-width: 768px)",
      "description": "targets viewports m and larger"
    },
    "value": "(min-width: 768px)",
    "attributes": {
      "category": "customMedia"
    }
  },
  {
    "mqInfo": {
      "size": "l",
      "usage": "@media (--viewport-l)",
      "query": "(min-width: 1024px)",
      "description": "targets viewports l and larger"
    },
    "value": "(min-width: 1024px)",
    "attributes": {
      "category": "customMedia"
    }
  },
  {
    "mqInfo": {
      "size": "xl",
      "usage": "@media (--viewport-xl)",
      "query": "(min-width: 1280px)",
      "description": "targets viewports xl and larger"
    },
    "value": "(min-width: 1280px)",
    "attributes": {
      "category": "customMedia"
    }
  }
];
export const layouts = [
  {
    "varNames": {
      "css": "var(--media-xs)",
      "js": "MEDIA_XS",
      "human": "xs"
    },
    "value": "18px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--media-s)",
      "js": "MEDIA_S",
      "human": "s"
    },
    "value": "24px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--media-m)",
      "js": "MEDIA_M",
      "human": "m"
    },
    "value": "32px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--media-l)",
      "js": "MEDIA_L",
      "human": "l"
    },
    "value": "50px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--media-xl)",
      "js": "MEDIA_XL",
      "human": "xl"
    },
    "value": "72px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-xs)",
      "js": "SPACE_XS",
      "human": "xs"
    },
    "value": "4px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-s)",
      "js": "SPACE_S",
      "human": "s"
    },
    "value": "8px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-m)",
      "js": "SPACE_M",
      "human": "m"
    },
    "value": "16px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-l)",
      "js": "SPACE_L",
      "human": "l"
    },
    "value": "24px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-xl)",
      "js": "SPACE_XL",
      "human": "xl"
    },
    "value": "32px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--space-default)",
      "js": "SPACE_DEFAULT",
      "human": "default"
    },
    "value": "16px",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--zindex-navigation)",
      "js": "ZINDEX_NAVIGATION",
      "human": "navigation"
    },
    "value": "10",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--zindex-modal)",
      "js": "ZINDEX_MODAL",
      "human": "modal"
    },
    "value": "20",
    "attributes": {
      "category": "layout"
    }
  },
  {
    "varNames": {
      "css": "var(--zindex-crazy)",
      "js": "ZINDEX_CRAZY",
      "human": "crazy"
    },
    "value": "50",
    "attributes": {
      "category": "layout"
    }
  }
];
export const fonts = [
  {
    "varNames": {
      "css": "var(--font-color-link)",
      "js": "FONT_COLOR_LINK",
      "human": "link"
    },
    "value": "#006699",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-linkInverted)",
      "js": "FONT_COLOR_LINK_INVERTED",
      "human": "linkInverted"
    },
    "value": "#4cabce",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-heading)",
      "js": "FONT_COLOR_HEADING",
      "human": "heading"
    },
    "value": "#404040",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-primary)",
      "js": "FONT_COLOR_PRIMARY",
      "human": "primary"
    },
    "value": "rgba(64, 64, 64, 0.87)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-secondary)",
      "js": "FONT_COLOR_SECONDARY",
      "human": "secondary"
    },
    "value": "rgba(64, 64, 64, 0.60)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-hint)",
      "js": "FONT_COLOR_HINT",
      "human": "hint"
    },
    "value": "rgba(64, 64, 64, 0.38)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-headingInverted)",
      "js": "FONT_COLOR_HEADING_INVERTED",
      "human": "headingInverted"
    },
    "value": "#ffffff",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-primaryInverted)",
      "js": "FONT_COLOR_PRIMARY_INVERTED",
      "human": "primaryInverted"
    },
    "value": "rgba(255, 255, 255, 0.87)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-secondaryInverted)",
      "js": "FONT_COLOR_SECONDARY_INVERTED",
      "human": "secondaryInverted"
    },
    "value": "rgba(255, 255, 255, 0.60)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-hintInverted)",
      "js": "FONT_COLOR_HINT_INVERTED",
      "human": "hintInverted"
    },
    "value": "rgba(255, 255, 255, 0.38)",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-error)",
      "js": "FONT_COLOR_ERROR",
      "human": "error"
    },
    "value": "#e5323e",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-success)",
      "js": "FONT_COLOR_SUCCESS",
      "human": "success"
    },
    "value": "#00986b",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-errorInverted)",
      "js": "FONT_COLOR_ERROR_INVERTED",
      "human": "errorInverted"
    },
    "value": "#e5323e",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-color-successInverted)",
      "js": "FONT_COLOR_SUCCESS_INVERTED",
      "human": "successInverted"
    },
    "value": "#70c390",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-family-condensed)",
      "js": "FONT_FAMILY_CONDENSED",
      "human": "condensed"
    },
    "value": "'Roboto Condensed', 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, sans-serif",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-family-default)",
      "js": "FONT_FAMILY_DEFAULT",
      "human": "default"
    },
    "value": "Roboto, 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, sans-serif",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-family-mono)",
      "js": "FONT_FAMILY_MONO",
      "human": "mono"
    },
    "value": "Monaco, Consolas, monospace",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-lineHeight-bigText)",
      "js": "FONT_LINE_HEIGHT_BIG_TEXT",
      "human": "bigText"
    },
    "value": "1.2",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-lineHeight-default)",
      "js": "FONT_LINE_HEIGHT_DEFAULT",
      "human": "default"
    },
    "value": "1.5",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-lineHeight-smallText)",
      "js": "FONT_LINE_HEIGHT_SMALL_TEXT",
      "human": "smallText"
    },
    "value": "1.8",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-xs)",
      "js": "FONT_SIZE_XS",
      "human": "xs"
    },
    "value": "10px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-s)",
      "js": "FONT_SIZE_S",
      "human": "s"
    },
    "value": "12px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-m)",
      "js": "FONT_SIZE_M",
      "human": "m"
    },
    "value": "14px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-default)",
      "js": "FONT_SIZE_DEFAULT",
      "human": "default"
    },
    "value": "14px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-l)",
      "js": "FONT_SIZE_L",
      "human": "l"
    },
    "value": "16px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-xl)",
      "js": "FONT_SIZE_XL",
      "human": "xl"
    },
    "value": "20px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-2xl)",
      "js": "FONT_SIZE_2XL",
      "human": "2xl"
    },
    "value": "24px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-3xl)",
      "js": "FONT_SIZE_3XL",
      "human": "3xl"
    },
    "value": "32px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-size-4xl)",
      "js": "FONT_SIZE_4XL",
      "human": "4xl"
    },
    "value": "38px",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-weight-default)",
      "js": "FONT_WEIGHT_DEFAULT",
      "human": "default"
    },
    "value": "400",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-weight-medium)",
      "js": "FONT_WEIGHT_MEDIUM",
      "human": "medium"
    },
    "value": "500",
    "attributes": {
      "category": "font"
    }
  },
  {
    "varNames": {
      "css": "var(--font-weight-bold)",
      "js": "FONT_WEIGHT_BOLD",
      "human": "bold"
    },
    "value": "700",
    "attributes": {
      "category": "font"
    }
  }
];
export const borders = [
  {
    "varNames": {
      "css": "var(--border-color-input)",
      "js": "BORDER_COLOR_INPUT",
      "human": "input"
    },
    "value": "rgba(64, 64, 64, 0.24)",
    "attributes": {
      "category": "border"
    }
  },
  {
    "varNames": {
      "css": "var(--border-color-focusRing)",
      "js": "BORDER_COLOR_FOCUS_RING",
      "human": "focusRing"
    },
    "value": "rgba(76, 171, 206, 0.6)",
    "attributes": {
      "category": "border"
    }
  },
  {
    "varNames": {
      "css": "var(--border-radius-default)",
      "js": "BORDER_RADIUS_DEFAULT",
      "human": "default"
    },
    "value": "4px",
    "attributes": {
      "category": "border"
    }
  }
];
export const motions = [
  {
    "varNames": {
      "css": "var(--motion-easing-default)",
      "js": "MOTION_EASING_DEFAULT",
      "human": "default"
    },
    "value": "cubic-bezier(0.4, 0, 0.2, 1)",
    "attributes": {
      "category": "motion"
    }
  },
  {
    "varNames": {
      "css": "var(--motion-easing-decelerate)",
      "js": "MOTION_EASING_DECELERATE",
      "human": "decelerate"
    },
    "value": "cubic-bezier(0, 0, 0.2, 1)",
    "attributes": {
      "category": "motion"
    }
  },
  {
    "varNames": {
      "css": "var(--motion-easing-accelerate)",
      "js": "MOTION_EASING_ACCELERATE",
      "human": "accelerate"
    },
    "value": "cubic-bezier(0.4, 0, 1, 1)",
    "attributes": {
      "category": "motion"
    }
  }
];