/**
* DO NOT EDIT
* Generated by fds-dictionary on Thu Nov 11 2021 15:24:47 GMT-0600 (Central Standard Time)
* github.com/cbinsights/form-design-system/
*/


const reactNative = {
  charcoal: '#404040',
  slate: '#757575',
  gray: '#A2A0A0',
  silver: '#C2BFBF',
  timberwolf: '#D6D4D4',
  lightgray: '#F2F2F2',
  white: '#FFFFFF',
  navy: '#003366',
  blue: '#006699',
  aqua: '#4CABCE',
  sky: '#BBDBE5',
  haze: '#f1f5f7',
  red: '#E5323E',
  orange: '#FF6633',
  sienna: '#F9A862',
  sand: '#FCC89A',
  green: '#00986B',
  mint: '#70C390',
  purple: '#A02385',
  violet: '#D772AD',
};
export default reactNative;