/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Nov 11 2021 14:32:55 GMT-0600 (Central Standard Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const CollectionPublicIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M5,2 L19,2 L19,22 L12,17 L5,22 L5,2 Z M7,4 L7,18 L12,14 L17,18 L17,4 L7,4 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default CollectionPublicIcon;

