/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const CreditcardIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<g transform="translate(2.000000, 4.000000)">
				<path d="M1.6,0 L18.4,0 C19.2836556,0 20,0.7163444 20,1.6 L20,4 L20,4 L0,4 L0,1.6 C0,0.7163444 0.7163444,0 1.6,0 Z"/>
				<path d="M20,6 L20,14.3333333 C20,15.2538079 19.2836556,16 18.4,16 L1.6,16 C0.7163444,16 0,15.2538079 0,14.3333333 L0,6 L20,6 Z M3.6,12.6666667 L1.2,12.6666667 C0.979086104,12.6666667 0.8,12.8532147 0.8,13.0833333 C0.8,13.313452 0.979086104,13.5 1.2,13.5 L1.2,13.5 L3.6,13.5 C3.8209139,13.5 4,13.313452 4,13.0833333 C4,12.8532147 3.8209139,12.6666667 3.6,12.6666667 L3.6,12.6666667 Z M9.2,12.6666667 L5.2,12.6666667 C4.9790861,12.6666667 4.8,12.8532147 4.8,13.0833333 C4.8,13.313452 4.9790861,13.5 5.2,13.5 L5.2,13.5 L9.2,13.5 C9.42091392,13.5 9.6,13.313452 9.6,13.0833333 C9.6,12.8532147 9.42091392,12.6666667 9.2,12.6666667 L9.2,12.6666667 Z"/>
			</g>
		</g>
	</g>
</svg>
  </div>
);

export default CreditcardIcon;

