/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Wed Aug 10 2022 09:54:14 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const CreditcardIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g transform="translate(2.000000, 4.000000)">
			<rect height="16" width="20" rx="2"/>
			<rect height="2.133" width="20" y="4.267"/>
			<rect height="1.067" width="3.158" rx=".533" x="1.053" y="12.8"/>
			<rect height="1.067" width="5.263" rx=".533" x="5.211" y="12.8"/>
		</g>
	</g>
</svg>
  </div>
);

export default CreditcardIcon;

