/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const DownloadOutlinedIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M10.5,2 C9.6829372,2 9,2.6829372 9,3.5 L9,10 L4.5859375,10 L12,17.414062 L19.414062,10 L15,10 L15,3.5 C15,2.6829372 14.317063,2 13.5,2 L10.5,2 Z M11,4 L13,4 L13,12 L14.585938,12 L12,14.585938 L9.4140625,12 L11,12 L11,4 Z M2,20 L2,22 L22,22 L22,20 L2,20 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default DownloadOutlinedIcon;

