/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Fri Dec 23 2022 12:08:31 GMT-0500 (Colombia Standard Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const DragIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<g transform="translate(2.000000, 7.000000)">
				<polygon points="4.95454545 9.90909091 0 4.95454545 4.95454545 0 6.23636364 1.28181818 3.48181818 4.04545455 16.5181818 4.04545455 13.7636364 1.28181818 15.0454545 0 20 4.95454545 15.0454545 9.90909091 13.7636364 8.62727273 16.5181818 5.86363636 3.48181818 5.86363636 6.23636364 8.62727273"/>
			</g>
		</g>
	</g>
</svg>
  </div>
);

export default DragIcon;

