/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const EditIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M3.00076581,14.4593369 L3,14.036437 C9.88566169,7.15452682 13.4220704,3.62024409 13.6092262,3.4335888 C14.1888947,2.8554704 15.3482318,2.8554704 15.9279003,3.4335888 L20.5652486,8.05853601 C21.1449171,8.63665441 21.1449171,9.79289121 20.5652486,10.3710096 L9.91320597,20.9945669 L9.55820081,20.9953897 L9.55820081,21 L3,21 L3,14.4593369 L3.00076581,14.4593369 Z M4.6395502,14.6917519 L4.6395502,18.1384599 L5.86921286,19.3648342 L9.21188354,19.3648342 L17.0861617,11.5261736 L12.4498891,6.90229921 L13.6092262,5.7460624 L18.2465745,10.3710096 C19.0194658,9.60018508 19.4020915,9.21599954 19.3945635,9.21845301 L14.7658542,4.60108581 C14.374312,4.98587536 13.9900902,5.36621689 13.6131888,5.74211042 L4.6395502,14.6917519 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default EditIcon;

