/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const MenuCloseIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<path d="M16.4444444,17.1111111 L16.4444444,19.3333333 L2,19.3333333 L2,17.1111111 L16.4444444,17.1111111 Z M20.4333333,7.11111111 L22,8.65555556 L18.0444444,12.6666667 L22,16.6777778 L20.4333333,18.2222222 L14.8666667,12.6666667 L20.4333333,7.11111111 Z M13.1111111,11.5555556 L13.1111111,13.7777778 L2,13.7777778 L2,11.5555556 L13.1111111,11.5555556 Z M16.4444444,6 L16.4444444,8.22222222 L2,8.22222222 L2,6 L16.4444444,6 Z" transform="translate(12.000000, 12.666667) scale(-1, 1) translate(-12.000000, -12.666667)"/>
		</g>
	</g>
</svg>
  </div>
);

export default MenuCloseIcon;

