/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Wed Dec 14 2022 11:46:36 GMT-0600 (Central Standard Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const PlantIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<path d="M2,21.0609663 L2,19.0609663 C2,19.0609663 7,17.0609663 12,17.0609663 C17,17.0609663 22,19.0609663 22,19.0609663 L22,21.0609663 L2,21.0609663"/>
			<path d="M11.3,8.16096632 C10.1,4.26096632 4,5.16096632 4,5.16096632 C4,5.16096632 4.2,12.9609663 9.9,11.7609663 C9.5,8.86096632 8,8.06096632 8,8.06096632 C10.8,8.06096632 11,11.4609663 11,11.4609663 L11,16.0609663 C11.3,16.0609663 11.7,16.0609663 12,16.0609663 C12.3,16.0609663 12.7,16.0609663 13,16.0609663 L13,11.8609663 C13,11.8609663 13,7.96096632 16,6.96096632 C16,6.96096632 14,9.96096632 14,11.9609663 C21,12.6609663 21,3.06096632 21,3.06096632 C21,3.06096632 12.1,2.06096632 11.3,8.16096632 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default PlantIcon;

