/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Fri Dec 23 2022 12:15:19 GMT-0500 (Colombia Standard Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const PlantIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<g transform="translate(2.000000, 3.000000)">
				<path d="M0,18.0609663 L0,16.0609663 C0,16.0609663 5,14.0609663 10,14.0609663 C15,14.0609663 20,16.0609663 20,16.0609663 L20,18.0609663 L0,18.0609663"/>
				<path d="M9.3,5.16096632 C8.1,1.26096632 2,2.16096632 2,2.16096632 C2,2.16096632 2.2,9.96096632 7.9,8.76096632 C7.5,5.86096632 6,5.06096632 6,5.06096632 C8.8,5.06096632 9,8.46096632 9,8.46096632 L9,13.0609663 C9.3,13.0609663 9.7,13.0609663 10,13.0609663 C10.3,13.0609663 10.7,13.0609663 11,13.0609663 L11,8.86096632 C11,8.86096632 11,4.96096632 14,3.96096632 C14,3.96096632 12,6.96096632 12,8.96096632 C19,9.66096632 19,0.0609663161 19,0.0609663161 C19,0.0609663161 10.1,-0.939033684 9.3,5.16096632 Z"/>
			</g>
		</g>
	</g>
</svg>
  </div>
);

export default PlantIcon;

