/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const PresentIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M4,2 C2.9069372,2 2,2.9069372 2,4 L2,20 C2,21.093063 2.9069372,22 4,22 L20,22 C21.093063,22 22,21.093063 22,20 L22,4 C22,2.9069372 21.093063,2 20,2 L4,2 Z M4,4 L20,4 L20,20 L4,20 L4,4 Z M8,7 L8,17 L17,12 L8,7 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default PresentIcon;

