/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const PublishIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M12,3 C9.6655084,3 7.7006133,4.2494956 6.4296875,6.0136719 C2.8854572,6.05389 0,8.9465993 0,12.5 C0,16.078268 2.9217323,19 6.5,19 L9,19 L9,17 L6.5,17 C4.0022677,17 2,14.997732 2,12.5 C2,10.002268 4.0022677,8 6.5,8 C6.534993,8 6.6164592,8.0069899 6.75,8.0136719 L7.3613281,8.0449219 L7.6660156,7.5136719 C8.5301088,6.0123517 10.137881,5 12,5 C14.504527,5 16.55398,6.8254912 16.931641,9.2148438 L17.083984,10.175781 L18.048828,10.050781 C18.272182,10.021699 18.414903,10 18.5,10 C20.444423,10 22,11.555577 22,13.5 C22,15.444423 20.444423,17 18.5,17 L15,17 L15,19 L18.5,19 C21.525577,19 24,16.525577 24,13.5 C24,10.509638 21.577034,8.0762027 18.599609,8.0195312 C17.729938,5.1415745 15.152096,3 12,3 Z M12,9 L8,13 L11,13 L11,21 L13,21 L13,13 L16,13 L12,9 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default PublishIcon;

