/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const SortUpIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M2,5 L2,7 L7,7 L7,5 L2,5 Z M19,21 L19,7 L22,7 L18,3 L14,7 L17,7 L17,21 L19,21 Z M2,9 L2,11 L9,11 L9,9 L2,9 Z M2,13 L2,15 L11,15 L11,13 L2,13 Z M2,17 L2,19 L13,19 L13,17 L2,17 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default SortUpIcon;

