/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Jun 09 2022 11:47:55 GMT-0400 (Eastern Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const StarHalfIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g fillRule="nonzero">
			<path d="M12.0009377,2.5 L8.89763261,8.78601253 L1.9609375,9.79490067 L6.98093766,14.6883636 L5.79610392,21.5978261 L12.0009377,18.3349252 L12.0009377,14.6883636 L12,11.8234827 L12.0009377,9.79490067 L12,9.02995489 L12.0009377,2.5 Z M15.436,8.329 L12.0009378,1.3705089 L8.565,8.329 L0.886598774,9.44589416 L6.443,14.863 L5.13205272,22.5119458 L12.001,18.899 L18.8698232,22.5119458 L17.557,14.862 L23.1152762,9.44589416 L15.436,8.329 Z M9.22964458,9.24298467 L12,3.629 L14.7722305,9.24298467 L20.966,10.143 L16.4837057,14.5138019 L17.541,20.683 L12.0009377,17.7700063 L6.459,20.684 L7.51816955,14.5138019 L3.034,10.143 L9.22964458,9.24298467 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default StarHalfIcon;

