/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const TextIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M5,3 C4.67998483,3 3.3466515,3 1,3 L1,7 L2,7 C2,11.2222222 2,14.5555556 2,17 L1,17 L1,21 L5,21 L5,20 C8.33333333,20 13,20 19,20 C19,20 19,20.3333333 19,21 L23,21 L23,17 L22,17 C22,14.7777778 22,11.4444444 22,7 C22,7 22.3333333,7 23,7 C23,7 23,3 23,3 L19,3 L19,4 C15.8325542,4 11.1772598,4 5,4 L5,3 Z M5,7 L5,6 L19,6 L19,7 L20,7 L20,17 L19,17 L19,18 L5,18 L5,17 L4,17 L4,7 L5,7 Z M9,8 L9,10 L11,10 L11,16 L13,16 L13,10 L15,10 L15,8 L13,8 L11,8 L9,8 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default TextIcon;

