/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const UnlockIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M18,9 L17,9 L17,6 C17,3.24 14.76,1 12,1 C9.24,1 7,3.24 7,6 L7,9 L6,9 C4.9,9 4,9.9 4,11 L4,20 C4,21.1 4.9,22 6,22 L18,22 C19.1,22 20,21.1 20,20 L20,11 C20,9.9 19.1,9 18,9 Z M9,5.5 C9,4.11666667 10.34,3 12,3 C13.66,3 15,4.11666667 15,5.5 C15,5.72222222 15,5.88888889 15,6 L17,6 L17,9 L15,9 L9,9 L9,5.5 Z M18,11 L18,20 L6,20 L6,11 L18,11 Z M14,15 L10,15 L10,17 L14,17 L14,15 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default UnlockIcon;

