/**
  * DO NOT EDIT',
  * Generated by fds-dictionary on Thu Aug 11 2022 10:23:19 GMT-0500 (Central Daylight Time)
  * github.com/cbinsights/form-design-system/
  */

import React from 'react';
import { IconProps } from 'components/Icon';

const WarningIcon = ({
  size = 's',
  color,
  customSize,
}: IconProps): JSX.Element => (
  <div
    className={`fds-icon fds-icon--${size}`}
    style={{
      fill: color,
      width: customSize && `${customSize}px`,
      height: customSize && `${customSize}px`,
    }}
  >
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<g fillRule="evenodd">
		<g>
			<path d="M21,20 L3,20 L12,4 L21,20 Z M11.9996739,2 C11.4562945,2 10.9118151,2.29058824 10.5785278,2.87058824 L1.27398062,19.0588235 C0.545808238,20.3270588 1.35427758,22 2.69622669,22 L21.304221,22 C22.6461701,22 23.4546395,20.3270588 22.7253671,19.0588235 L13.42082,2.87058824 C13.0875326,2.29058824 12.5430533,2 11.9996739,2 L11.9996739,2 Z M11,9 L11,15 L13,15 L13,9 L11,9 Z M11,17 L11,19 L13,19 L13,17 L11,17 Z"/>
		</g>
	</g>
</svg>
  </div>
);

export default WarningIcon;

