/**
 * @param {String} path SVG path (xml)
 * @param {String} iconName name of icon
 * @returns {String} file content for icon react component
 */
const createIconComponent = (path, iconName) =>
  `/* Generated by fds-icons */
import React from 'react';
import SvgIcon from '@material-ui/core/SvgIcon';

const ${iconName} = (props) => (
  <SvgIcon {...props}>
    ${path}
  </SvgIcon>
);

export default ${iconName};
\n`;

module.exports = createIconComponent;
