/**
 * @param {String} svgJsx jsx-valid SVG
 * @param {String} iconName name of icon
 * @returns {String} file content for icon react component
 */
const createIconComponent = (svgJsx, iconName) =>
  `/* Generated by fds-icons */
import React from 'react';
import PropTypes from 'prop-types';
import SvgIcon from '@material-ui/core/SvgIcon';

const styles = {
  shapeRendering: 'geometricPrecision'
};

const ${iconName} = (props) => (
  <SvgIcon {...props} style={styles}>
    ${svgJsx}
  </SvgIcon>
);

${iconName}.defaultProps = {
  color: '#404040'
};

${iconName}.propTypes = {
  color: PropTypes.string
};

export default ${iconName};
\n`;

module.exports = createIconComponent;
