const fs = require('fs');
const Handlebars = require('handlebars');
const { toHsla } = require('./util/color');

Handlebars.registerHelper('json', (c) => JSON.stringify(c, null, 2));
const template = Handlebars.compile(fs.readFileSync(`./doc/index.hbs`).toString());

/**
 * @returns {String} generated comment with date
 */
const jsComment = () =>
  [
    '/**',
    '* DO NOT EDIT',
    `* Generated by fds-dictionary on ${new Date()}`,
    '* github.com/cbinsights/form-design-system/',
    '*/\n\n',
  ].join('\n');

/**
 * @param {Array} dictionary style-dictionary dictionary
 * @return {String} html file
 */
const formatHtmlDoc = (dictionary) => {
  const colors = dictionary.allProperties
    .filter((p) => p.attributes.category === 'color')
    .map((p) => {
      const { hex, rgb, hsl, varNames } = p.attributes;

      return {
        name: p.name,
        varNames,
        values: {
          calculated: p.value,
          hex,
          rgba: `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${rgb.a})`,
          hsla: toHsla(hsl),
        },
      };
    });

  return template({
    properties: {
      colors,
    },
  });
};

/**
 * @param {Array} dictionary style-dicitonary dictionary
 * @return {String} js file with commonJS exports
 */
const formatCommonJs = (dictionary) =>
  jsComment() +
  dictionary.allProperties
    .filter((prop) => prop.attributes.category !== 'font') // encourage CSS classes for type styles
    .map((prop) => `exports.${prop.name} = '${prop.value}';`)
    .join('\n');

/**
 * @param {dictionary} dictionary style-dictionary dictionary
 * @return {String} js file for colors in the CBI React Native app
 */
const formatReactNativeColors = (dictionary) =>
  [
    `${jsComment()}`,
    'module.exports = {',
    ...dictionary.allProperties
      .filter((prop) => prop.attributes.category === 'color')
      .map((prop) => `  ${prop.name}: '${prop.value}',`),
    '};',
  ].join('\n');

// Custom formats
module.exports = [
  {
    name: 'html/doc',
    formatter: formatHtmlDoc,
  },
  {
    name: 'javascript/commonJs',
    formatter: formatCommonJs,
  },
  {
    name: 'javascript/reactNativeColors',
    formatter: formatReactNativeColors,
  },
];
