export const mockOptions = [
  {
    id: 'apple',
    text: 'apple',
    label: 'apple',
    value: 'apple',
    type: 'entity',
    category: 'Search term',
    defaultType: 'Search term',
    uid: 'apple-3dd5511b-379a-4523-9d98-fdeb72c758b5',
    targetTab: 'company',
  },
  {
    id: 'apple',
    text: 'apple',
    label: 'apple',
    value: 'apple',
    type: 'entity',
    category: 'Search term',
    defaultType: 'Research search term',
    uid: 'apple-research-3dd5511b-379a-4523-9d98-fdeb72c758b5',
    targetTab: 'research',
  },
  {
    category: 'Organization',
    compoundId: '1581112103',
    text: 'Apple',
    value: 'apple.com',
    type: 'entity',
    url: 'apple.com',
    uid: 'edyp',
    extraInfo: 'apple.com',
    defaultType: 'company',
    idCompany: 15811,
    idInvestor: 12103,
    idOrg: 13528,
    label: 'Apple',
    id: 13528,
  },
  {
    category: 'Collection',
    defaultType: 'collection',
    idCollection: 19723,
    idTeam: 121,
    idUser: [1759217, 96358, 46583],
    isExpert: true,
    text: "Apple's Investments + M&A",
    type: 'entity',
    uid: 'ncqi',
    label: "Apple's Investments + M&A",
  },
  {
    category: 'Collection',
    defaultType: 'collection',
    idCollection: 418609,
    idTeam: 121,
    idUser: [3381919],
    isExpert: false,
    text: "Apple's Investments + M&A (Cloned on 2/24/2020)",
    type: 'entity',
    uid: 'nh3s',
    label: "Apple's Investments + M&A (Cloned on 2/24/2020)",
  },
  {
    category: 'Collection',
    defaultType: 'collection',
    idCollection: 544265,
    idTeam: 39630,
    idUser: [3381919],
    isExpert: false,
    text: "Apple's Investments + M&A (Cloned on 8/26/2020)",
    type: 'entity',
    uid: '7j8i',
    label: "Apple's Investments + M&A (Cloned on 8/26/2020)",
  },
  {
    category: 'Organization',
    compoundId: '18365476025',
    text: 'ApplePie Capital',
    value: 'applepiecapital.com',
    type: 'entity',
    url: 'applepiecapital.com',
    uid: 'dlun',
    extraInfo: 'applepiecapital.com',
    defaultType: 'company',
    idCompany: 183654,
    idInvestor: 76025,
    idOrg: 209319,
    label: 'ApplePie Capital',
    id: 209319,
  },
];
