on:
  pull_request:
    branches: ['master', 'beta']
  push:
    branches: ['master', 'beta']

jobs:
  test:
    uses: cbinsights/form-design-system/.github/workflows/test.yml@beta
  typecheck:
    uses: cbinsights/form-design-system/.github/workflows/typecheck.yml@beta
  linting:
    uses: cbinsights/form-design-system/.github/workflows/linting.yml@beta
