name: Pull request

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    uses: cbinsights/form-design-system/.github/workflows/reusable-test.yml@master
  typecheck:
    uses: cbinsights/form-design-system/.github/workflows/reusable-typecheck.yml@master
  lint:
    uses: cbinsights/form-design-system/.github/workflows/reusable-linting.yml@master
  cypress-test:
    steps:
      - name: Every time
        run: echo "${GITHUB_HEAD_REF}"
    uses: cbinsights/form-design-system/.github/workflows/reusable-cypress-test.yml@rename-cypress-test
