name: Pull request

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    uses: cbinsights/form-design-system/.github/workflows/reusable-test.yml@master
  typecheck:
    uses: cbinsights/form-design-system/.github/workflows/reusable-typecheck.yml@master
  lint:
    uses: cbinsights/form-design-system/.github/workflows/reusable-linting.yml@master
  cypress-test:
    uses: cbinsights/form-design-system/.github/workflows/cypress-test.yml
