name: Cypress Tests

on:
  workflow_call:

jobs:
  cypress-test:
    name: Cypress test Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Yarn Install
        run: yarn --immutable

      - name: Test Storybook with Cypress
        run: yarn ci:start-and-test-storybook
