name: Reusable workflow example

on:
  workflow_call:

jobs:
  example_job:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
