name: Reusable workflow example

on:
  workflow_call:

jobs:
  example_job:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --frozen-lockfile
