name: Linting reusable workflow

on:
  workflow_call:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --frozen-lockfile
      - name: Build Style Dictionary
        run: yarn build
      - name: Run eslint
        run: yarn lint
      - name: Run Prettier Check
        run: yarn prettier:check
