name: Reusable workflow example

on:
  workflow_call:

jobs:
  install:
    name: Installing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn --frozen-lockfile
