name: Beta versions

on:
  pull_request:
    branches: ['beta']
  push:
    branches: ['beta']

jobs:
  # test:
  #   uses: cbinsights/form-design-system/.github/workflows/test.yml@beta
  # typecheck:
  #   uses: cbinsights/form-design-system/.github/workflows/typecheck.yml@beta
  # lint:
  #   uses: cbinsights/form-design-system/.github/workflows/linting.yml@beta
  npm-beta:
    name: Publish npm beta version
    # needs: [test, typecheck, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
          always-auth: true
      # - name: Yarn Install
      #   run: yarn --frozen-lockfile
      # - name: Build Package
      #   run: yarn build
      - run: yarn publish --new-version 11.11.${GITHUB_RUN_ID}-beta.${GITHUB_SHA::8} --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
